### ISSUE TITLE
GRAD-GPAD dataset

### ISSUE THREAD

**Issue by spthakkar** [acostapazo/gradgpad#14]
I have followings questions related to platform,
Are all datasets required to be present to test your platform?
 What if I want to use my algorithms with your datasets?

**Comment by acostapazo** [comment]
First of all, thanks to share your questions, I'm trying to answer your questions.

> Are all datasets required to be present to test your platform?

It is not necessary, although the more datasets you add to the test, the greater the statistical significance of your evaluation set. 

`"The unified categorisation added in GRAD-GPAD v2 brings the opportunity both to create novel protocols and to visualise the results from different perspectives. Also, the extended GRAD-GPAD v2 dataset allows a better statistical significance of the results of previous protocols, leveraging their added-value for assessing face-PAD generalisation on current and future algorithms."`

In this [link](https://raw.githubusercontent.com/acostapazo/gradgpad/main/gradgpad/data/gradgpad_annotations.json), we share the annotations of the 13 datasets, but you can use only what you have available. Check the following code to filter the annotation by dataset.

```python
from gradgpad import annotations

my_datasets = ["replay-mobile", "replay-attack"]

selected_annotations = [
     annotation
     for annotation in annotations.annotated_samples
     if annotation.dataset.value in my_datasets
]
```

---

> What if I want to use my algorithms with your datasets?

Sounds great. For this you will have to integrate your code for the annotations, and if you want to use the visualization tools the annotation files will have to follow a format like [this](https://github.com/acostapazo/gradgpad/tree/main/gradgpad/data/scores/auxiliary).

```python
from gradgpad import annotations

my_datasets = ["replay-mobile", "replay-attack"]

path_datasets = {
    "replay-mobile": "/Users/username/datasets/replay-mobile",  # set path to your dataset
    "replay-attack": "/Users/username/datasets/replay-attack",  # set path to your dataset
}

annotations.print_semantic(0)
for annotation in annotations.annotated_samples:
    
    # skip if datataset is not in my_datasets
    if  annotation.dataset.value not in my_datasets:
      continue

    filename = f"{path_datasets.get(annotation.dataset)}/{annotation.media}"
    print(f"{filename=}")

    # load the media file

    # execute your algorithm

    # save to a file like this {annotation.media: score}
    # like in https://github.com/acostapazo/gradgpad/tree/main/gradgpad/data/scores/auxiliary


# once you have the score files, you can use the evaluation tools
# check notebooks in https://github.com/acostapazo/gradgpad-notebooks
```

**Comment by acostapazo** [comment]
I've added a FAQ section in README.md to clarify this questions :)
